### ISSUE TITLE
Could we get a "Hello World" example? 

### ISSUE THREAD

**Issue by ScottyEfird** [h313/spet#3]
Ie, a Spoty playlist of songs that would generate a hello world type output. Thanks.

**Comment by lalevac** [comment]
I made a playlist that outputs `HELLO WORLD`.
Spotify URI: `spotify:user:modonoob:playlist:2PBKAHNnevhQFv3BH54Fqr`

![](http://modonoob.net/captures/mintty_2018-10-15_19-25-03.png)

**Comment by h313** [comment]
Here's one I made for the demo: https://open.spotify.com/user/wh313/playlist/7hShQSKY5AU0YQaN833iEx?si=ZkdPnEkCQYyhpGNE9px_ZQ
